name: drunk-api
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12beta1
      uses: actions/setup-go@v1
      with:
        go-version: 1.12beta1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:

    - name: Test
      run: go test ./infrastructure/datastore/
